name <- c("Sambit1", "Sambit2", "Sambit3")
marks <- c(12.5, 9, 16.5)
roll <- c(11, 13, 12)
result <- c("yes", "no", "yes")
df <- data.frame(name, marks, roll, result)
print("Original dataframe:")
print(df)
print("Structure of the said data frame:")
print(str(df))