num_vec = c(1, 2, 3, 3, 4, NA, 3, 2, 4, 5, NA, 5)
print("Original vector:")
print(num_vec)
print("Factors of the vector")
num_vec<-factor(c(1,2,3,4,NA, 3,2,4,NA, 5))
print(num_vec)
print("Levels of factor of the said vector:")
